### ISSUE TITLE
Invalid path alias: @Vitalik74/wysihtml5/assets

### ISSUE THREAD

**Issue by ruslanmedia** [vitalik74/yii2-bootstrap-wysihtml5-widget#1]
How to fix Invalid path alias: @Vitalik74/wysihtml5/assets error

foreach (static::$aliases[$root] as $name => $path) {
                    if (strpos($alias . '/', $name . '/') === 0) {
                        return $path . substr($alias, strlen($name));
                    }
                }
            }
        }

```
    if ($throwException) {
        throw new InvalidParamException("Invalid path alias: $alias"); // error line
    } else {
        return false;
    }
}

/**
 * Returns the root alias part of a given alias.
 * A root alias is an alias that has been registered via [[setAlias()]] previously.
 * If a given alias matches multiple root aliases, the longest one will be returned
```

**Comment by vitalik74** [comment]
Thanks for pull
